/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables


import io.github.novemdecillion.carioncrawler.adapter.jooq.DefaultSchema
import io.github.novemdecillion.carioncrawler.adapter.jooq.keys.ACCOUNT_PKEY
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.records.AccountRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AccountTable(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AccountRecord>?,
    aliased: Table<AccountRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AccountRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>account</code>
         */
        val ACCOUNT = AccountTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AccountRecord> = AccountRecord::class.java

    /**
     * The column <code>account.username</code>.
     */
    val USERNAME: TableField<AccountRecord, String?> = createField(DSL.name("username"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>account.password</code>.
     */
    val PASSWORD: TableField<AccountRecord, String?> = createField(DSL.name("password"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>account.role</code>.
     */
    val ROLE: TableField<AccountRecord, String?> = createField(DSL.name("role"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AccountRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AccountRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>account</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>account</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>account</code> table reference
     */
    constructor(): this(DSL.name("account"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AccountRecord>): this(Internal.createPathAlias(child, key), child, key, ACCOUNT, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<AccountRecord> = ACCOUNT_PKEY
    override fun getKeys(): List<UniqueKey<AccountRecord>> = listOf(ACCOUNT_PKEY)
    override fun `as`(alias: String): AccountTable = AccountTable(DSL.name(alias), this)
    override fun `as`(alias: Name): AccountTable = AccountTable(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AccountTable = AccountTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AccountTable = AccountTable(name, null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<String?, String?, String?> = super.fieldsRow() as Row3<String?, String?, String?>
}
