/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables


import io.github.novemdecillion.carioncrawler.adapter.jooq.DefaultSchema
import io.github.novemdecillion.carioncrawler.adapter.jooq.keys.SEARCHED_PAGE_PKEY
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.records.SearchedPageRecord

import java.time.OffsetDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SearchedPageTable(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SearchedPageRecord>?,
    aliased: Table<SearchedPageRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SearchedPageRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>searched_page</code>
         */
        val SEARCHED_PAGE = SearchedPageTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SearchedPageRecord> = SearchedPageRecord::class.java

    /**
     * The column <code>searched_page.url</code>.
     */
    val URL: TableField<SearchedPageRecord, String?> = createField(DSL.name("url"), SQLDataType.VARCHAR(2047).nullable(false), this, "")

    /**
     * The column <code>searched_page.create_at</code>.
     */
    val CREATE_AT: TableField<SearchedPageRecord, OffsetDateTime?> = createField(DSL.name("create_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SearchedPageRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SearchedPageRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>searched_page</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>searched_page</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>searched_page</code> table reference
     */
    constructor(): this(DSL.name("searched_page"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SearchedPageRecord>): this(Internal.createPathAlias(child, key), child, key, SEARCHED_PAGE, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<SearchedPageRecord> = SEARCHED_PAGE_PKEY
    override fun getKeys(): List<UniqueKey<SearchedPageRecord>> = listOf(SEARCHED_PAGE_PKEY)
    override fun `as`(alias: String): SearchedPageTable = SearchedPageTable(DSL.name(alias), this)
    override fun `as`(alias: Name): SearchedPageTable = SearchedPageTable(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SearchedPageTable = SearchedPageTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SearchedPageTable = SearchedPageTable(name, null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<String?, OffsetDateTime?> = super.fieldsRow() as Row2<String?, OffsetDateTime?>
}
