/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables


import io.github.novemdecillion.carioncrawler.adapter.jooq.DefaultSchema
import io.github.novemdecillion.carioncrawler.adapter.jooq.keys.STATE_PKEY
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.records.StateRecord

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class StateTable(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, StateRecord>?,
    aliased: Table<StateRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<StateRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>state</code>
         */
        val STATE = StateTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<StateRecord> = StateRecord::class.java

    /**
     * The column <code>state.key</code>.
     */
    val KEY: TableField<StateRecord, String?> = createField(DSL.name("key"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>state.value</code>.
     */
    val VALUE: TableField<StateRecord, String?> = createField(DSL.name("value"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<StateRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<StateRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>state</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>state</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>state</code> table reference
     */
    constructor(): this(DSL.name("state"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, StateRecord>): this(Internal.createPathAlias(child, key), child, key, STATE, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<StateRecord> = STATE_PKEY
    override fun getKeys(): List<UniqueKey<StateRecord>> = listOf(STATE_PKEY)
    override fun `as`(alias: String): StateTable = StateTable(DSL.name(alias), this)
    override fun `as`(alias: Name): StateTable = StateTable(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): StateTable = StateTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): StateTable = StateTable(name, null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<String?, String?> = super.fieldsRow() as Row2<String?, String?>
}
