/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.keys


import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.CrawledPageTable
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.FlywaySchemaHistoryTable
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.SearchedPageTable
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.StateTable
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.records.CrawledPageRecord
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.records.FlywaySchemaHistoryRecord
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.records.SearchedPageRecord
import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.records.StateRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val CRAWLED_PAGE_PKEY: UniqueKey<CrawledPageRecord> = Internal.createUniqueKey(CrawledPageTable.CRAWLED_PAGE, DSL.name("crawled_page_pkey"), arrayOf(CrawledPageTable.CRAWLED_PAGE.URL), true)
val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val SEARCHED_PAGE_PKEY: UniqueKey<SearchedPageRecord> = Internal.createUniqueKey(SearchedPageTable.SEARCHED_PAGE, DSL.name("searched_page_pkey"), arrayOf(SearchedPageTable.SEARCHED_PAGE.URL), true)
val STATE_PKEY: UniqueKey<StateRecord> = Internal.createUniqueKey(StateTable.STATE, DSL.name("state_pkey"), arrayOf(StateTable.STATE.KEY), true)
