/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables.interfaces


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IAccount : Serializable {
    var username: String?
    var password: String?
    var role: String?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAccount
     */
    fun from(from: IAccount)

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAccount
     */
    fun <E : IAccount> into(into: E): E
}
