/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables.interfaces


import io.github.novemdecillion.carioncrawler.adapter.db.CrawledStatus

import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ICrawledPage : Serializable {
    var url: String?
    var status: CrawledStatus?
    var note: String?
    var exclude: Boolean?
    var searchedAt: OffsetDateTime?
    var crawledAt: OffsetDateTime?
    var html: String?
    var `data`: ByteArray?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICrawledPage
     */
    fun from(from: ICrawledPage)

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICrawledPage
     */
    fun <E : ICrawledPage> into(into: E): E
}
