/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.time.LocalDate


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ISearchKeyword : Serializable {
    var keyword: String?
    var searchedAt: LocalDate?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISearchKeyword
     */
    fun from(from: ISearchKeyword)

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISearchKeyword
     */
    fun <E : ISearchKeyword> into(into: E): E
}
