/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables.interfaces


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ISearchedPage : Serializable {
    var url: String?
    var createAt: OffsetDateTime?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISearchedPage
     */
    fun from(from: ISearchedPage)

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISearchedPage
     */
    fun <E : ISearchedPage> into(into: E): E
}
