/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables.interfaces


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IState : Serializable {
    var key: String?
    var value: String?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IState
     */
    fun from(from: IState)

    /**
     * Copy data into another generated Record/POJO implementing the common interface IState
     */
    fun <E : IState> into(into: E): E
}
