app:
  selenide-crawl:
    cron: 0 10 4 * * *
    store-folder: ./reports
    max-depth: 20

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/carion-crawler
    username: admin
    password: password123
    hikari:
      maximum-pool-size: 1
      minimum-idle: 5

  flyway:
    clean-on-validation-error: true
