/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables.pojos


import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.interfaces.IAccount


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class AccountEntity(
    override var username: String? = null, 
    override var password: String? = null, 
    override var role: String? = null
): IAccount {


    override fun toString(): String {
        val sb = StringBuilder("AccountEntity (")

        sb.append(username)
        sb.append(", ").append(password)
        sb.append(", ").append(role)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IAccount) {
        username = from.username
        password = from.password
        role = from.role
    }

    override fun <E : IAccount> into(into: E): E {
        into.from(this)
        return into
    }
}
