/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables.pojos


import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.interfaces.ISearchKeyword

import java.time.LocalDate


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SearchKeywordEntity(
    override var keyword: String? = null, 
    override var searchedAt: LocalDate? = null
): ISearchKeyword {


    override fun toString(): String {
        val sb = StringBuilder("SearchKeywordEntity (")

        sb.append(keyword)
        sb.append(", ").append(searchedAt)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: ISearchKeyword) {
        keyword = from.keyword
        searchedAt = from.searchedAt
    }

    override fun <E : ISearchKeyword> into(into: E): E {
        into.from(this)
        return into
    }
}
