/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables.pojos


import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.interfaces.ISearchedPage

import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SearchedPageEntity(
    override var url: String? = null, 
    override var createAt: OffsetDateTime? = null
): ISearchedPage {


    override fun toString(): String {
        val sb = StringBuilder("SearchedPageEntity (")

        sb.append(url)
        sb.append(", ").append(createAt)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: ISearchedPage) {
        url = from.url
        createAt = from.createAt
    }

    override fun <E : ISearchedPage> into(into: E): E {
        into.from(this)
        return into
    }
}
