/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.carioncrawler.adapter.jooq.tables.pojos


import io.github.novemdecillion.carioncrawler.adapter.jooq.tables.interfaces.IState


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class StateEntity(
    override var key: String? = null, 
    override var value: String? = null
): IState {


    override fun toString(): String {
        val sb = StringBuilder("StateEntity (")

        sb.append(key)
        sb.append(", ").append(value)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IState) {
        key = from.key
        value = from.value
    }

    override fun <E : IState> into(into: E): E {
        into.from(this)
        return into
    }
}
